// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2m58GohhSwfGUTA0WAxJ_oFuitHBtWCQ',
    appId: '1:979886460479:web:1b5c929d40f57bc080328a',
    messagingSenderId: '979886460479',
    projectId: 'angel-95750',
    authDomain: 'angel-95750.firebaseapp.com',
    storageBucket: 'angel-95750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc0TiAe2lwsbzBJO4WF-ZdiALPQKy2qTY',
    appId: '1:979886460479:ios:064aae5bc6ed062980328a',
    messagingSenderId: '979886460479',
    projectId: 'angel-95750',
    storageBucket: 'angel-95750.firebasestorage.app',
    iosBundleId: 'com.ridy.taxi.driver',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Oa2zoMVqGXAhPEbWXDsIKSHMdTIWR2g',
    appId: '1:979886460479:android:0f19c58673d9908780328a',
    messagingSenderId: '979886460479',
    projectId: 'angel-95750',
    storageBucket: 'angel-95750.firebasestorage.app',
  );

}